AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Python Layers and role from S3

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: iata-dev-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

      Policies:
        - PolicyName: LambdaS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - arn:aws:s3:::iata-data-lake-demo
                  - arn:aws:s3:::iata-data-lake-demo/*
          
  PandasLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: demo-1
      Description: libraries
      Content:
        S3Bucket: iata-data-lake-demo
        S3Key: layers/requests.zip
      CompatibleRuntimes:
        - python3.12
        - python3.11